n=input("enter your name")
b=input ("enter your branch")
g=input("enter your gender")
c=input("enter your college")
a=int(input("enter your age"))
print("name:",n)
print ("branch:",b)
print ("gender:",g)
print("college:",c)
print("age:",a)
